extends SceneTree
const Fixture = preload("res://tests/fixture.gd")
var checks:=0
var failures:=0
func check(ok:bool,label:String)->void:
	checks+=1
	if not ok: failures+=1;printerr("FAIL: ",label)
func _initialize()->void: call_deferred("run")
func run()->void:
	var game=Fixture.create_game()
	root.add_child(game)
	await process_frame
	game.set_process(false)
	var test_time:int=game.store.now()
	game.store.clock=func():return test_time
	game.store.regenerate()
	game.store.apply(func(s):s.story.opening=true;s.gold=12345;return true)
	game._show_lobby()
	var home=game.screen_view
	check(home.gold_value.text=="12,345","Gold is read from the save, not baked into art")
	check(home.level_value.text=="LEVEL 1" and home.progress_value.text=="0 / 10","Level and chapter dots use actual progress")
	check(home.get_node_or_null("RewardsButton")==null,"Redundant bronze reward chest is removed")
	check(home.shortcuts.size()==6,"Six illustrated shortcuts are available on the Safehouse")
	for button in home.shortcuts.values():
		check(not button.get_rect().intersects(home.nodes.CaseFile.get_rect()),"Standard side targets clear lower actions: "+button.name)
	var before_shortcuts:Dictionary=game.store.state.duplicate(true)
	home.shortcuts.chapter.pressed.emit()
	check(home.rewards.visible and game.store.state==before_shortcuts,"Milestone shortcut previews rewards without granting or changing progress")
	check(home.nodes.PlayButton.focus_mode==Control.FOCUS_NONE,"Reward overview excludes background keyboard focus")
	home._close_rewards()
	check(home.shortcuts.chapter.has_focus() and home.nodes.PlayButton.focus_mode==Control.FOCUS_ALL,"Closing restores shortcut focus and Safehouse controls")
	home.shortcuts.no_ads.pressed.emit()
	check(game.modal_kind=="offer" and game.overlay.get_node("Card").get_meta("product_id","")=="no_ads" and game.store.state==before_shortcuts,"No Ads opens its exact product without a purchase")
	game._close_modal()
	home.get_node("Gear").pressed.emit()
	check(game.modal_kind=="settings","Gear opens Settings")
	game._close_modal()
	home.get_node("EnergyHit").pressed.emit()
	check(game.modal_kind=="out_of_energy","Energy remains accessible")
	game._close_modal()
	home.shortcuts.daily.pressed.emit()
	check(home.rewards.visible and home.reward_buttons.size()==6,"Every old reward action remains reachable")
	home.reward_buttons.daily.pressed.emit()
	check(game.modal_kind=="reward" and not home.rewards.visible,"Daily reward closes the tray and uses the existing reward flow")
	game._close_modal()
	var before:Dictionary=game.store.state.duplicate(true)
	game.commerce.fake_ad_status="skipped"
	home.shortcuts.coins.pressed.emit();await process_frame
	check(game.store.state.gold==before.gold,"Skipped video shortcut grants no gold")
	game.commerce.fake_ad_status="rewarded"
	home.shortcuts.coins.pressed.emit();await process_frame
	check(game.modal_kind=="reward" and game.store.state.gold==before.gold+int(game.store.rules.free_coins_gold),"Watch Ad shortcut uses the verified provider reward flow")
	game._close_modal()
	game.store.restore_entitlement("no_ads_pack")
	for i in int(game.store.rules.free_coins_daily_cap):game.store.grant_ad_reward("free_coins","shortcut-cap-%d"%i)
	home.refresh()
	check(home.shortcuts.no_ads.disabled and home.reward_buttons.no_ads.disabled,"Either No Ads entitlement disables repeat purchase entry")
	check(home.shortcuts.coins.disabled and home.reward_buttons.coins.disabled,"Exhausted daily ads disable both entry points")
	before=game.store.state.duplicate(true)
	home.get_node("CaseFile").pressed.emit()
	check(game.screen=="story" and game.screen_view.archive_mode,"Case File reuses the story screen")
	check(game.screen_view.archive_view.rows.size()==10 and game.screen_view.archive_view.rows[0].scenes.size()==1,"Case File starts with ten stage cards and the current opening only")
	game.screen_view._skip()
	check(game.screen=="lobby" and game.store.state==before,"Archive exit neither starts a heist nor changes progress/rewards")
	game.store.mark_story(game.campaign.chapters[0].id)
	before=game.store.state.duplicate(true)
	game.screen_view.get_node("CaseFile").pressed.emit()
	var archive=game.screen_view.archive_view
	check(archive.rows[0].scenes.size()==1 and not archive.rows[1].unlocked,"A midway story does not unlock the stage finale")
	archive.open_stage(1)
	archive.next_scene()
	check(archive.mode=="directory" and game.store.state==before,"Last archive scene returns to the directory without changing the save")
	archive._back()
	game.screen_view.get_node("NavGallery").pressed.emit()
	check(game.screen=="gallery","Museum opens the existing collection")
	game._show_lobby()
	game.screen_view.get_node("Avatar").pressed.emit()
	check(game.screen=="gallery","Avatar opens Crew")
	game._show_lobby()
	game.screen_view.get_node("NavShop").pressed.emit()
	check(game.screen=="shop","Shop opens its real screen")
	game._show_lobby()
	game.screen_view.set_anchors_and_offsets_preset(Control.PRESET_TOP_LEFT)
	game.screen_view.size=Vector2(720,1558)
	game.screen_view._layout()
	for button in game.screen_view.shortcuts.values():
		check(not button.get_rect().intersects(game.screen_view.nodes.CaseFile.get_rect()),"Side targets clear lower actions: "+button.name)
	check(game.screen_view.get_node("PlayButton").position.y==1267,"Tall screens anchor play near the bottom")
	check(game.screen_view.get_node("NavGallery").position.y==1418,"Tall screens keep navigation at the bottom")
	game.screen_view.get_node("PlayButton").pressed.emit()
	check(game.screen=="play","Start Heist launches the next puzzle")
	game._show_lobby()
	for level in game.levels:game.store.record_win(level.art_id,"",3)
	game.screen_view.refresh()
	check(game.screen_view.nodes.PlayButton.disabled and game.screen_view.nodes.PlayButton.get_node("Caption").text=="More Soon","Exhausted authored content disables the launch CTA and uses an honest caption")
	Fixture.cleanup(game)
	game.queue_free()
	await process_frame
	print("LOBBY CHECKS: %d | FAILURES: %d" %[checks,failures])
	quit(1 if failures else 0)
