#!/usr/bin/env python3
"""Generate gettext resources from the English source and complete locale files."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('en', 'tr', 'es', 'de')
PLACEHOLDER = re.compile(r'\{([a-z_]+)\}')

def catalogs():
    source = json.loads((ROOT / 'localization/source.json').read_text())
    translations = {lang: json.loads((ROOT / f'localization/{lang}.json').read_text())
                    for lang in LANGUAGES if lang != 'en'}
    english = {key: {'one': entry['text'], 'other': entry['plural']}
               if 'plural' in entry else entry['text'] for key, entry in source.items()}
    translations['en'] = english
    for lang, data in translations.items():
        assert set(data) == set(source), f'{lang}: missing/extra keys'
        for key, value in data.items():
            plural = 'plural' in source[key]
            assert isinstance(value, dict) == plural, (lang, key, 'plural shape')
            variants = list(value.values()) if plural else [value]
            if plural:
                assert set(value) == {'one', 'other'}, (lang, key)
            expected = set(PLACEHOLDER.findall(source[key]['text']))
            for text in variants:
                assert isinstance(text, str) and text.strip(), (lang, key, 'empty')
                assert set(PLACEHOLDER.findall(text)) == expected, (lang, key, 'placeholders')
                assert '\ufffd' not in text, (lang, key, 'encoding')
    return source, translations

def render(source, data, locale):
    quote = lambda s: json.dumps(s, ensure_ascii=False)
    lines = ['# Generated by tools/build_localization.py; edit localization JSON sources.',
             'msgid ""', 'msgstr ""',
             quote('Content-Type: text/plain; charset=UTF-8\n'),
             quote(f'Language: {locale}\n'),
             quote('Plural-Forms: nplurals=2; plural=(n != 1);\n'), '']
    for key, entry in sorted(source.items()):
        lines += ['#. ' + entry['note'], '#. English: ' + entry['text'].replace('\n', ' / ')]
        if entry['context']:
            lines.append('msgctxt ' + quote(entry['context']))
        lines.append('msgid ' + quote(key))
        if 'plural' in entry:
            lines += ['msgid_plural ' + quote(key + '.plural'),
                      'msgstr[0] ' + quote(data[key]['one']),
                      'msgstr[1] ' + quote(data[key]['other'])]
        else:
            lines.append('msgstr ' + quote(data[key]))
        lines.append('')
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source, translations = catalogs()
    for lang in LANGUAGES:
        path = ROOT / f'localization/{lang}.po'
        expected = render(source, translations[lang], lang)
        if args.check:
            assert path.read_text() == expected, f'Stale gettext output: {path}'
        else:
            path.write_text(expected)
    for name, fields in [('levels', ['title', 'mission', 'room', 'intro', 'outro', 'clue', 'speaker_key', 'end_speaker_key']),
                         ('artwork_details', ['artist', 'date', 'museum', 'description']),
                         ('locations', ['city', 'country', 'context'])]:
        for row in json.loads((ROOT / f'data/{name}.json').read_text()):
            for field in fields:
                assert row[field] in source, (name, row['art_id'], field)
            for fact in row.get('facts', []):
                assert fact in source, fact
    # Check literal references in all scene/script entry points, including prototypes.
    prefixes = {key.split('.')[0] for key in source}
    for path in [*ROOT.glob('scripts/**/*.gd'), *ROOT.glob('scenes/**/*.tscn')]:
        for key in re.findall(r'"([a-z]+\.[a-z_][a-z_0-9.]*)"', path.read_text()):
            if key.split('.')[0] in prefixes:
                assert key in source or (key.endswith('_') and any(item.startswith(key) for item in source)), (str(path.relative_to(ROOT)), key, 'unknown text key')
    for identity, name in {'rocco':'Rocco “Pixel”', 'sprocket':'Sprocket', 'quill':'Quill',
                           'frost':'Mr. Frost', 'glimmer':'Baron Glimmer', 'tuck':'Tuck', 'barnaby':'Barnaby Bramble'}.items():
        for locale, data in translations.items():
            assert data['speaker.' + identity] == name, (locale, identity, 'canonical name')
        assert source['speaker.' + identity]['context'] == 'speaker'
    assert (ROOT / 'docs/Localization.md').exists(), 'Missing authoring/context glossary'
    print(f'Localization OK: {len(source)} keys × en/tr/es/de; contexts, plurals, placeholders and generated PO files match')

if __name__ == '__main__':
    main()
